### ISSUE TITLE
Test for challenge 3 (schema) fails intermittently

### ISSUE THREAD

**Issue by JamesLMilner** [nearform/the-graphql-workshop#228]
The test case for challenge 3 intermittently fails due to a timeout:

```shell
  ---
  env: {}
  file: src/step-03-executable-schema/test/schema.test.js
  timeout: 30000
  command: /opt/hostedtoolcache/node/16.16.0/x64/bin/node
  args:
    - src/step-03-executable-schema/test/schema.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/runner/work/the-graphql-workshop/the-graphql-workshop
  exitCode: null
  signal: SIGTERM
  ...
````

Here are a couple GitHub Action runs where it fails:

https://github.com/nearform/the-graphql-workshop/runs/7464913563?check_suite_focus=true#step:8:228
https://github.com/nearform/the-graphql-workshop/runs/7421785836?check_suite_focus=true#step:8:86

Investigating this a bit more it gets interesting. Initially I was unable to reproduce it locally, but using nvm and switching to the CI Node version (16.16.0) I was able to reproduce it (intermittently as in CI).

### Reproduction

Here is a short script you can place in the folder (`step-03-executable-schema`) that generally reproduces the issue when 16.16.0 - normally around the 15th or so iteration for me. 

```javascript
import child_process  from 'child_process';

function testFailed(cmd, i) {
  try {
    child_process.execSync(cmd);
    return false;
  } 
  catch (error) {
    console.log("failed on iteration: ", i)
    return true;
  }
};

for (let i = 0; i < 30; i++) {
  console.log("test run", i);
  const failed = testFailed('npm run test', i)
  if (failed) {
    break;
  }
}
```

### Ways that seem to resolve the issue:

* Using Node 18
* If I remove `c8` from `npm run test`
* Replacing schema in `index.js` with:
```javascript

  const schema = `
    type Query {
      add(x: Int, y: Int): Int
    }
  `

  const resolvers = {
    Query: {
      add: async (_, obj) => {
        const { x, y } = obj
        return x + y
      }
    }
  }

 
  server.register(mercurius, {
    schema,
    resolvers
    })
 ```
 * Removing this part of the test:
 ```javascript
  const response = await server.inject({
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    url: '/graphql',
    payload: JSON.stringify({ query })
  })
```
### Potentially related issues

I found this [issue](https://github.com/ardatan/graphql-tools/issues/4346) on graphql-tools that relates to the usage of `makeExecutableSchema` and people experiencing issues on CI.

**Comment by simoneb** [comment]
This seems to be failing fairly consistently now. A good way to approach this would be to see when this problem started. Possibly a dependency bump

**Comment by nasainsbury** [comment]
Downgraing to `mercius 10.0.0` seems to have fixed it for me.

Tested a few times. Will create a PR and see if you're happy with the solution.

![Image](https://user-images.githubusercontent.com/58425475/182412183-c51767de-574f-4235-8a75-d2e8209559cb.png)

**Comment by nasainsbury** [comment]
Raised an issue about this too: https://github.com/mercurius-js/mercurius/issues/835

**Comment by nasainsbury** [comment]
Very odd, if you change the `index.js` code to be

```js
import Fastify from 'fastify'
import mercurius from 'mercurius'
import { makeExecutableSchema } from '@graphql-tools/schema'

import { schema, resolvers } from './graphql.js'

export default function buildServer() {
  const server = Fastify({
    logger: {
      transport: {
        target: 'pino-pretty'
      }
    }
  })

  server.register(mercurius, {
    schema,
    resolvers,
    graphiql: true
  })

  return server
}
```

It still doesn't work, however by just removing `import { makeExecutableSchema } from '@graphql-tools/schema'` it does. I'm not sure where to go from here, I've looked through the code for `makeExecutableSchema`, but my context on the repo and GraphQL in general is too low to properly diagnose the issue

**Comment by simoneb** [comment]
I think we need to come up with a minimal repro and, if the issue is indeed in mercurius, report it there. The current issue we have in that repo doesn't call for any maintainer's time to look into what the issue is, because it's unclear if it's mercurius or our code
